[package]
name = "rpr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.8"
reqwest = "0.11.22"
serde = "1.0.192"
serde_json = "1.0.108"
